# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factory', '0002_tarea_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tareas',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.Project'),
        ),
    ]
